/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: victory_mirosya (https://sketchfab.com/victory_mirosya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-f372c04de44640fbb6a4f9e4e5845c78
Title: Fox
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import PropTypes from 'prop-types';
import scene from '../assets/3d/monster2.glb';

export default function Fox({ currentAnimation, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50.762}
        >
          <group name="8031fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="8031">
                  <group name="GameObject" scale={1.25}>
                    <group
                      name="F1_xueqilinzuoqi"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={1.25}
                    />
                    <group name="root">
                      <group name="Object_8">
                        <primitive object={nodes._rootJoint} />
                        <skinnedMesh
                          name="Object_11"
                          geometry={nodes.Object_11.geometry}
                          material={materials['8031_Material']}
                          skeleton={nodes.Object_11.skeleton}
                        />
                        <group
                          name="Object_10"
                          rotation={[-Math.PI / 2, 0, 0]}
                          scale={[1.562, 1.563, 1.563]}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
Fox.propTypes = {
  currentAnimation: PropTypes.string,
};
